### ISSUE TITLE
Squished Comment Section

### ISSUE THREAD

**Issue by ryanjamesdev** [cohhe/longform#1]
My entire comment section is squished and not sitting properly here is an example:
http://1000epics.com/2016/getting-it-done-january-update/

**Comment by Sprincis** [comment]
Hi there, there's an extra CSS style ( at style.css line: 4281 ) that's causing this issue and I can't find it in any of our commits, so I guess you have edited the CSS yourself? Also you're using Longform version 1.6.1 while the newest one is 1.6.5, consider updating your theme.
