### ISSUE TITLE
Undefined Variable error on Authors Bio Page

### ISSUE THREAD

**Issue by ryanjamesdev** [cohhe/longform#2]
'
Notice: Undefined variable: author_style in /home/spiri803/public_html/1000epics.com/wp-content/themes/longform/author.php on line 54

Notice: Undefined variable: social_content in /home/spiri803/public_html/1000epics.com/wp-content/themes/longform/author.php on line 72
'

Here is an example:
http://1000epics.com/author/epic_admin/

**Comment by Sprincis** [comment]
Hello, I fixed those notices and released version 1.6.5 for Longform.
